typedef enum {
    TYPE_PRIMITIVE_I32,
    TYPE_META_NONE,
    TYPE_META_ANY,
    TYPE_META_EXPRESSION,
    TYPE_META_TYPE,
    TYPE_META_TOKEN,
    TYPE_META_PROJECTILE,
    TYPE_META_MESSAGE,
    TYPE_BASIC__END
} EType_Basic;